name: Build gamescope snapshot
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: thevakhovske/holoiso:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v2
      
      - name: Prepare pacman keyring
        run: |
          pacman --noconfirm -S base-devel fakeroot dos2unix git wget meson wayland-protocols ninja glslang vulkan-headers
          find . -type f -print0 | xargs -0 dos2unix
          chown -R nobody:nobody .
          git config --global protocol.file.allow always
          
      - name: Prepare dependencies
        run: |   
          pacman -S --noconfirm $(cat PKGBUILD | grep depends | cut -d "=" -f 2 | sed "s/(//g;s/)//g;s/'//g")
          
      - name: Build Arch package
        run: |
          su -s /bin/bash nobody -c "makepkg -s && mkdir pkgout && mv *.tar.zst pkgout"
          
      - name: Add to arch repository
        run: |
          su -s /bin/bash nobody -c "wget http://dlcdn2.thevakhovske.pw/holoiso/os/x86_64/holoiso.db -P pkgout"
          su -s /bin/bash nobody -c "wget http://dlcdn2.thevakhovske.pw/holoiso/os/x86_64/holoiso.db.tar.gz -P pkgout"
          su -s /bin/bash nobody -c "wget http://dlcdn2.thevakhovske.pw/holoiso/os/x86_64/holoiso.db.tar.gz.old -P pkgout"
          su -s /bin/bash nobody -c "wget http://dlcdn2.thevakhovske.pw/holoiso/os/x86_64/holoiso.db.tar.xz -P pkgout"
          su -s /bin/bash nobody -c "wget http://dlcdn2.thevakhovske.pw/holoiso/os/x86_64/holoiso.files -P pkgout"
          su -s /bin/bash nobody -c "wget http://dlcdn2.thevakhovske.pw/holoiso/os/x86_64/holoiso.files.tar.gz -P pkgout"
          su -s /bin/bash nobody -c "wget http://dlcdn2.thevakhovske.pw/holoiso/os/x86_64/holoiso.files.tar.gz.old -P pkgout"
          su -s /bin/bash nobody -c "wget http://dlcdn2.thevakhovske.pw/holoiso/os/x86_64/holoiso.files.tar.xz -P pkgout"
          su -s /bin/bash nobody -c "repo-add pkgout/holoiso.db.tar.gz pkgout/*.tar.zst"
      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: pkgout/*
